-- This module is the root of the VojtaConjectureCanonicalLaneLean Lean proof package.
import VojtaConjectureCanonicalLaneLean.Basic
import VojtaConjectureCanonicalLaneLean.SourcePackage
import VojtaConjectureCanonicalLaneLean.SourceDependencies
import VojtaConjectureCanonicalLaneLean.Formalization
import VojtaConjectureCanonicalLaneLean.ReviewerBridge
import VojtaConjectureCanonicalLaneLean.TheoremStatement
import VojtaConjectureCanonicalLaneLean.MathlibObjects
import VojtaConjectureCanonicalLaneLean.AdmissibleClass
import VojtaConjectureCanonicalLaneLean.Projection
import VojtaConjectureCanonicalLaneLean.BridgeLemmas
import VojtaConjectureCanonicalLaneLean.GateLemmas
import VojtaConjectureCanonicalLaneLean.FinalTheorem
import VojtaConjectureCanonicalLaneLean.MathlibStatement
import VojtaConjectureCanonicalLaneLean.HeightInequalityLayer
